### ISSUE TITLE
Oracle Cloud Ampere A1 compatibility.

### ISSUE THREAD

**Issue by SavageTheUnicorn** [nsarrazin/serge#151]
### Bug description

So I tested this out on an instance under OCI and it worked well. Now, it is no longer returning anything in shell when "lscpu | grep avx2" is ran and remains loading forever after a question is asked. CPU usage spikes but RAM/Memory usage never seems to increase.

Again, about 1-2 weeks ago it worked flawlessly, it just took up to 2 minutes to generate a response. Now a response is never fully generated. Upon click refresh in the browser, PART of a response shows before the page actually loads proving that it IS working. Any ideas what to do?

### Steps to reproduce

Install Serge on OCI A1 4ocpu 24gb ram instance.
Download model
Ask question
Nothing

### Environment Information

Docker version 23.0.3, build 3e7cbfd
Ubuntu 22.04 LTS 
Oracle Cloud free tier
A1 Ampere instance

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by SavageTheUnicorn** [comment]
Yes @gaby

**Comment by snxraven** [comment]
Are you able to grab the containers log so we can see what the issue may be?

Best way is to use `docker logs containerName` since portainer will turn most output into "Objects"

**Comment by SavageTheUnicorn** [comment]
Sadly no, when I tried to check container names there were none listed. I was attempting to run this chat bot in tandem with Pterodactyl Panel which worked fine at first but as soon as I restarted/rebooted the instance neither the bot nor the panel functioned. Having to reset instance and wait another couple weeks to get another instance. I'm not trying this anymore haha...

**Comment by toasterrepairman** [comment]
Oracle offers a [pre-configured Pytorch image](https://cloudmarketplace.oracle.com/marketplace/en_US/adf.task-flow?tabName=O&adf.tfDoc=%2FWEB-INF%2Ftaskflow%2Fadhtf.xml&application_id=125935163&adf.tfId=adhtf) for Ampere instances. I've been using it to host Serge as an API and it works quite well for me, since finding native AArch64-accelerated libtorch is so hard. If you're not adverse to reinstalling the server, maybe give it a whirl and see how it runs. It might just be an issue with your current environment somehow too, you never really know with Python.

**Comment by SavageTheUnicorn** [comment]
Thanks @toasterrepairman. I'll look into it when I acquire another instance 🙃
